version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
    volumes:
      - ./assets/postgres/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./pg_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: post-comments
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_PASSWORD: "12345"


