version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: post_comment_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/post_comment_db?sslmode=disable

volumes:
  db_data: