// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package post_comments

type NewComment struct {
	PostID   int    `json:"postId"`
	ParentID *int   `json:"parentId,omitempty"`
	Body     string `json:"body"`
}

type NewPost struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}
